### ISSUE TITLE
Missing `components` folder in PR: Js documentation and Minor changes #14

### ISSUE THREAD

**Issue by wong-ja** [Chromium99/AlgeBlitz#16]
I think the `components` folder is missing from the recent merge, which is causing import errors in the `index.tsx` and `_layout.tsx` files. Could we check if this folder was/could be added?

**Comment by DeveloperMindset123** [comment]
Jair Added it to the recent PR, should work now as intended, apologies for the confusion.

**Comment by wong-ja** [comment]
Thanks for adding the components folder to the PR. I’ll pull the latest changes and check if the imports in index.tsx and _layout.tsx are working now. I’ll let you know if I run into any more issues.
